export const WORK_TASK_LOADING = "WORK_TASK_LOADING";
export const WORK_TASK_SUCCESS = "WORK_TASK_SUCCESS";
export const WORK_TASK_ERROR = "WORK_TASK_ERROR";

// Time Logs Stuff
export const TIME_LOGS_LOADING = "TIME_LOGS_LOADING";
export const TIME_LOGS_SUCCESS = "TIME_LOGS_SUCCESS";
export const TIME_LOGS_ERROR = "TIME_LOGS_ERROR";

// Time Log categories stuff
export const TIME_LOG_CATEGORIES_LOADING = "TIME_LOG_CATEGORIES_LOADING";
export const TIME_LOG_CATEGORIES_SUCCESS = "TIME_LOG_CATEGORIES_SUCCESS";
export const TIME_LOG_CATEGORIES_ERROR = "TIME_LOG_CATEGORIES_ERROR";

// Time Logs Delete Action
export const TIME_LOG_DELETE = "TIME_LOGS_DELETE";
export const TIME_LOG_DELETE_SUCCESS = "TIME_LOGS_DELETE_SUCCESS";
export const TIME_LOG_DELETE_ERROR = "TIME_LOGS_DELETE_ERROR";

// Time Logs Create Action
export const TIME_LOG_CREATE = "TIME_LOG_CREATE";
export const TIME_LOG_CREATE_SUCCESS = "TIME_LOG_CREATE_SUCCESS";
export const TIME_LOG_CREATE_ERROR = "TIME_LOG_CREATE_ERROR";
export const TIME_LOG_RESET = "TIME_LOG_RESET";

// Event Logs Stuff
export const EVENT_LOGS_LOADING = "EVENT_LOGS_LOADING";
export const EVENT_LOGS_SUCCESS = "EVENT_LOGS_SUCCESS";
export const EVENT_LOGS_ERROR = "EVENT_LOGS_ERROR";

// child work tasks stuff
export const CHILD_WORK_TASKS_LOADING = "CHILD_WORK_TASKS_LOADING";
export const CHILD_WORK_TASKS_SUCCESS = "CHILD_WORK_TASKS_SUCCESS";
export const CHILD_WORK_TASKS_ERROR = "CHILD_WORK_TASKS_ERROR";

// Service Request Stuff
export const SERVICE_REQUEST_LOADING = "SERVICE_REQUEST_LOADING";
export const SERVICE_REQUEST_SUCCESS = "SERVICE_REQUEST_SUCCESS";
export const SERVICE_REQUEST_ERROR = "SERVICE_REQUEST_ERROR";
