export const APP_INITIALIZE = "APP_INITIALIZE";
export const APP_INITIALIZED = "APP_INITIALIZED";
export const APP_INITIALIZATION_ERROR = "APP_INITIALIZATION_ERROR";
export const USER_LOGIN = "USER_LOGIN";
